#!/usr/bin/env bash
# Sales: a year of order lines, and the report a finance team asks for, built
# from aggregations alone -- no rows leave the engine except the summaries.
source "$(dirname "$0")/lib.sh"
IDX=sales
SUM=sales-monthly
ROLL=sales-daily
ROLLED=sales-daily-rollup
PAGES=/tmp/sales-24-buckets.ndjson

# ask METHOD PATH FILE -- reqf, keeping the answer in $ANSWER for the checks
ANSWER=
ask() {
  ANSWER=$("${CURL[@]}" -X "$1" "$BS$2" -H 'Content-Type: application/json' --data-binary "@$3")
  printf '%s\n' "$ANSWER"
}

# expect EXPR WANT [what] -- a Python expression over the last answer's
# aggregations (`a`) must print WANT; `other` is the same for $OTHER, when it is
# set. The wanted numbers were counted from data/make-sales.py's output by a
# separate script, not copied from a run.
expect() {
  local got
  got=$(printf '%s' "$ANSWER" | python3 -c 'import json,sys
import os
d = json.load(sys.stdin); a = d.get("aggregations", {})
other = json.loads(os.environ.get("OTHER") or "{}").get("aggregations", {})
try: print(eval(sys.argv[1]))
except Exception as e: print("error: %r" % e)' "$1")
  if [ "$got" = "$2" ]; then
    printf '   \033[32mok\033[0m  %s%s\n' "$got" "${3:+ -- $3}"
  else
    printf '   \033[31mNOT WHAT WAS EXPECTED\033[0m  %s, expected %s%s\n' "$got" "$2" "${3:+ -- $3}" >&2
    _fails=$((_fails + 1))
  fi
}

# job KIND ID FILE -- write a transform or a rollup job whose first run is a
# couple of seconds away rather than a minute: its schedule starts just under
# one period ago
job() {
  local path=/_plugins/_transform/$2
  [ "$1" = rollup ] && path=/_plugins/_rollup/jobs/$2
  local body
  body=$(python3 -c 'import json,sys,time
b = json.load(open(sys.argv[1]))
job = b.get("transform") or b.get("rollup")
job["schedule"]["interval"]["start_time"] = int(time.time() * 1000) - 58000
print(json.dumps(b))' "$3")
  ANSWER=$("${CURL[@]}" -X PUT "$BS$path" -H 'Content-Type: application/json' -d "$body")
  printf '%s\n' "$ANSWER" | clip 300
}

# finished KIND ID -- wait for a job to finish its run, and keep what explain
# says of it in $ANSWER, as `a` for the checks
finished() {
  local path=/_plugins/_transform/$2/_explain key=transform_metadata
  [ "$1" = rollup ] && path=/_plugins/_rollup/jobs/$2/_explain key=rollup_metadata
  local i=0 status=
  while [ "$i" -lt 150 ]; do
    ANSWER=$("${CURL[@]}" "$BS$path" | python3 -c 'import json,sys
d = json.load(sys.stdin)
print(json.dumps({"aggregations": (d.get(sys.argv[1]) or {}).get(sys.argv[2]) or {}}))' "$2" "$key")
    status=$(printf '%s' "$ANSWER" | python3 -c 'import json,sys; print(json.load(sys.stdin)["aggregations"].get("status", ""))')
    [ "$status" = finished ] || [ "$status" = failed ] && break
    i=$((i + 1)); sleep 1
  done
  printf '%s\n' "$ANSWER" | clip 400
}

step "an index shaped for aggregation: every field a keyword, a number or a date"
# a job left from an earlier run is stopped and deleted with its index, or it
# would write into the next run's summary while this one is still loading
"${CURL[@]}" -X POST "$BS/_plugins/_transform/$SUM/_stop" > /dev/null 2>&1 || true
gone "/_plugins/_transform/$SUM?force=true"
"${CURL[@]}" -X POST "$BS/_plugins/_rollup/jobs/$ROLL/_stop" > /dev/null 2>&1 || true
gone "/_plugins/_rollup/jobs/$ROLL"
gone "/$IDX"; gone "/$SUM"; gone "/$ROLLED"
reqf PUT "/$IDX" requests/01-an-index-shaped-for-aggregation.json
green "$IDX"

step "a year of sales lines, one document per line sold"
note "generated by data/make-sales.py with a fixed seed; 3,000 ordinary lines and 4 rare ones"
ndjson "/$IDX/_bulk?refresh=wait_for" data/01-a-year-of-sales-lines-one.ndjson | clip 200
expect_docs "$IDX" 3004 "a year of sales"

step "every region, category and month: a composite, paged with after_key until it runs out"
note "a terms aggregation would have to guess a size; a composite hands back a cursor instead"
: > "$PAGES"
after=""
page=0
while :; do
  body=$(python3 -c 'import json,sys
b = json.load(open(sys.argv[1]))
if sys.argv[2]: b["aggs"]["lines"]["composite"]["after"] = json.loads(sys.argv[2])
print(json.dumps(b))' requests/02-every-region-category-and-month-a.json "$after")
  out=$("${CURL[@]}" -X GET "$BS/$IDX/_search" -H 'Content-Type: application/json' -d "$body")
  page=$((page + 1))
  [ "$page" = 1 ] && printf '%s\n' "$out" | clip 700
  read -r n after < <(printf '%s' "$out" | python3 -c 'import json,sys
agg = json.load(sys.stdin)["aggregations"]["lines"]
with open(sys.argv[1], "a") as f:
    for b in agg["buckets"]: f.write(json.dumps(b) + "\n")
print(len(agg["buckets"]), json.dumps(agg["after_key"], sort_keys=True, separators=(",", ":")) if agg["buckets"] and "after_key" in agg else "")' "$PAGES")
  note "page $page: $n buckets${after:+, after_key $after}"
  [ "$n" = 0 ] || [ -z "$after" ] && break
  [ "$page" -gt 50 ] && { echo "the composite never ran out of pages" >&2; exit 1; }
done
ANSWER=$(python3 -c 'import json,sys
bs = [json.loads(l) for l in open(sys.argv[1])]
print(json.dumps({"aggregations": {"n": len(bs), "keys": len({json.dumps(b["key"], sort_keys=True) for b in bs}),
  "docs": sum(b["doc_count"] for b in bs), "revenue": sum(b["revenue"]["value"] for b in bs)}}))' "$PAGES")
expect 'a["n"], a["keys"]' "(240, 240)" "5 regions x 4 categories x 12 months, none repeated across pages"
expect 'a["docs"], round(a["revenue"], 2)' "(3004, 1030908.54)" "every sale counted once, and the whole year's revenue"

step "a summary index kept by a transform: one document per region, category and month"
note "the transform runs the same composite in pages of 100 and writes each bucket as a document,"
note "under an id worked out from its key -- run again, it overwrites rather than adds"
reqf PUT "/$SUM" requests/03-a-summary-index-built-from-those.json
green "$SUM"
job transform "$SUM" requests/16-a-transform-that-keeps-the-summary.json
finished transform "$SUM"
expect 'a["status"], a["stats"]["documents_processed"], a["stats"]["documents_indexed"]' "('finished', 3004, 240)" \
  "every sale read once, one document per group"
expect 'a["stats"]["pages_processed"]' "4" "three pages of buckets and the empty page that ends them"
quiet POST "/$SUM/_refresh"
expect_docs "$SUM" 240 "one document per composite bucket"
ANSWER=$("${CURL[@]}" "$BS/_plugins/_transform/$SUM")
printf '%s' "$ANSWER" | python3 -c 'import json,sys
t = json.load(sys.stdin)["transform"]
print("   the transform has turned itself off: enabled =", t["enabled"])'

step "the summary answers what the raw index answers, from 240 documents instead of 3004"
note "--- the raw index"
ask GET "/$IDX/_search" requests/04-the-summary-answers-what-the-raw.json
raw=$ANSWER
note "--- the summary"
ask GET "/$SUM/_search" requests/04-the-summary-answers-what-the-raw.json
OTHER=$raw expect '[(b["key"], round(b["revenue"]["value"], 2)) for b in a["regions"]["buckets"]] == [(b["key"], round(b["revenue"]["value"], 2)) for b in other["regions"]["buckets"]]' \
  "True" "every region's revenue is the same from either index"
expect 'round(a["total"]["value"], 2)' "1030908.54" "the year's revenue, from the summary"
note "--- a question only the summary is cheap for: the three best months"
ANSWER=$("${CURL[@]}" -X GET "$BS/$SUM/_search" -H 'Content-Type: application/json' -d '{
  "size": 0,
  "aggs": { "months": {
    "date_histogram": { "field": "month", "calendar_interval": "month", "format": "yyyy-MM" },
    "aggs": { "revenue": { "sum": { "field": "revenue" } },
              "best": { "bucket_sort": { "sort": [ { "revenue": { "order": "desc" } } ], "size": 3 } } } } }
}')
printf '%s\n' "$ANSWER"
expect '[b["key_as_string"] for b in a["months"]["buckets"]]' "['2025-12', '2025-11', '2025-10']" "the last quarter, as the generator weighted it"

step "a rollup of every day and region, searched as though it were the sales"
note "a rollup keeps sums and counts per bucket; a search of its index is rewritten against them,"
note "and a bucket counts the sales it stands for, not the rollup documents"
job rollup "$ROLL" requests/17-a-rollup-of-every-day-by-region.json
finished rollup "$ROLL"
expect 'a["status"], a["stats"]["documents_processed"], a["stats"]["rollups_indexed"], a["stats"]["pages_processed"]' \
  "('finished', 3004, 1382, 15)" "1382 days a region sold something, in pages of 100"
ask GET "/$ROLLED/_search" requests/04-the-summary-answers-what-the-raw.json
OTHER=$raw expect '[(b["key"], b["doc_count"], round(b["revenue"]["value"], 2)) for b in a["regions"]["buckets"]] == [(b["key"], b["doc_count"], round(b["revenue"]["value"], 2)) for b in other["regions"]["buckets"]]' \
  "True" "the same regions, the same sales counted, the same revenue as the raw index"
ANSWER=$("${CURL[@]}" -X GET "$BS/$ROLLED/_search" -H 'Content-Type: application/json' -d '{
  "size": 0,
  "query": { "term": { "region": "north" } },
  "aggs": { "average_sale": { "avg": { "field": "revenue" } }, "sales": { "value_count": { "field": "revenue" } } }
}')
printf '%s\n' "$ANSWER"
expect 'round(a["average_sale"]["value"], 2), a["sales"]["value"]' "(341.17, 932)" \
  "an average put back together from the sums and counts the rollup kept"
# refused with a 400, so asked without --fail-with-body
ANSWER=$(curl -sS -X GET "$BS/$ROLLED/_search" -H 'Content-Type: application/json' -d '{ "size": 10, "query": { "match_all": {} } }')
printf '%s\n' "$ANSWER" | clip 300
expect 'd["error"]["root_cause"][0]["reason"]' "Rollup search must have size explicitly set to 0, but found 10" \
  "a rollup has no single sales to show, and says so"

step "which region and channel pairs sell the most"
ask GET "/$IDX/_search" requests/05-which-region-and-channel-pairs-sell.json
expect '[b["key_as_string"] for b in a["pairs"]["buckets"]]' "['north|web', 'west|web', 'south|web', 'north|store', 'east|web']"
expect 'round(a["pairs"]["buckets"][0]["revenue"]["value"], 2)' "182720.74" "north through the web"

step "the products almost nobody bought"
ask GET "/$IDX/_search" requests/06-the-products-almost-nobody-bought.json
expect 'sorted((b["key"], b["doc_count"]) for b in a["hardly_sold"]["buckets"])' "[('globe', 1), ('hammock', 2), ('telescope', 1)]" "and nothing else"

step "the year in six buckets, whatever width that takes"
ask GET "/$IDX/_search" requests/07-the-year-in-six-buckets-whatever.json
expect 'a["year"]["interval"], len(a["year"]["buckets"])' "('3M', 4)" "the engine chose quarters: months would have been twelve buckets"
expect '[b["doc_count"] for b in a["year"]["buckets"]]' "[585, 636, 678, 1105]"

step "order sizes and quarters, named by hand and keyed"
ask GET "/$IDX/_search" requests/08-order-sizes-and-quarters-named-by.json
expect '[a["order_size"]["buckets"][k]["doc_count"] for k in ("small", "medium", "large")]' "[1783, 1006, 215]"
expect 'round(a["quarters"]["buckets"]["Q4"]["revenue"]["value"], 2)' "364103.81" "Q4 is a third of the year"

step "the biggest and the latest sale in each region"
ask GET "/$IDX/_search" requests/09-the-biggest-and-the-latest-sale.json
expect '[b["biggest"]["hits"]["hits"][0]["_id"] for b in a["regions"]["buckets"]]' "['SO-00903', 'SO-02289', 'SO-01014', 'SO-02379', 'SO-02291']"
expect '[b["latest"]["hits"]["hits"][0]["_source"]["sold_at"] for b in a["regions"]["buckets"]][-1]' "2025-12-31T18:34:00Z" "west's last sale of the year"

step "the shape of price, discount and revenue"
ask GET "/$IDX/_search" requests/10-the-shape-of-price-discount-and.json
expect '[(b["key"], round(b["price_paid_per_unit"]["value"], 2), round(b["plain_avg_price"]["value"], 2)) for b in a["by_category"]["buckets"]][1]' \
  "('electronics', 254.52, 273.67)" "a 20-unit order counts once in a plain average and twenty times in a weighted one"
expect 'round(a["discount"]["avg"], 4), round(a["discount"]["std_deviation"], 4), a["discount"]["max"]' "(0.082, 0.0575, 0.31)"
expect '{f["name"]: round(f["correlation"]["revenue"], 2) for f in a["together"]["fields"]}["quantity"] > 0' "True" "more units, more revenue"
note "the median and its absolute deviation are estimates; counted exactly they are 72.82 and 50.66"

step "regions ranked by margin, the weak ones dropped"
ask GET "/$IDX/_search" requests/11-regions-ranked-by-margin-the-weak.json
expect '[(b["key"], round(b["margin_pct"]["value"], 2)) for b in a["regions"]["buckets"]]' \
  "[('west', 36.17), ('north', 33.98), ('east', 32.59)]" "south (28.84) and central (24.12) fell below 30"

step "bulk orders, deep discounts, and everything else"
ask GET "/$IDX/_search" requests/12-bulk-orders-deep-discounts-and-everything.json
expect '[a["kinds"]["buckets"][k]["doc_count"] for k in ("bulk", "deep_discount", "neither")]' "[244, 127, 2642]" \
  "3013 in all: the filters overlap, nine sales are both"

step "central against the whole company, in one request"
ask GET "/$IDX/_search" requests/13-central-against-the-whole-company.json
expect 'round(a["central_revenue"]["value"], 2), a["company"]["doc_count"], round(a["company"]["revenue"]["value"], 2)' "(111189.49, 3004, 1030908.54)" \
  "the query scoped the first number; global ignored it"
expect 'round(a["central_discount"]["value"], 4), round(a["company"]["discount"]["value"], 4)' "(0.1777, 0.082)" "central discounts twice as deep"

step "what a missing field counts as"
ask GET "/$IDX/_search" requests/14-what-a-missing-field-counts-as.json
expect 'a["unrated"]["doc_count"], [b["doc_count"] for b in a["coupons"]["buckets"] if b["key"] == "(none)"][0]' "(574, 2553)"
expect 'round(a["rating_of_the_rated"]["value"], 2), round(a["rating_if_unrated_is_1"]["value"], 2)' "(3.96, 3.4)" \
  "the same field, averaged under two different beliefs about silence"

step "a value the documents do not store: the quarter, computed"
ask GET "/$IDX/_search" requests/15-a-value-the-documents-do-not.json
expect '[(b["key"], b["doc_count"]) for b in a["quarter"]["buckets"]]' "[('Q1', 585), ('Q2', 636), ('Q3', 678), ('Q4', 1105)]" \
  "the same counts date_range and auto_date_histogram gave"
expect '[(c["key"], c["doc_count"]) for c in a["quarter"]["buckets"][3]["basket"]["buckets"]]' "[('one or two', 746), ('several', 268), ('bulk', 91)]"

step "what this example leaves behind, checked rather than assumed"
expect_docs "$IDX" 3004 "the sales lines"
expect_docs "$SUM" 240 "the summary"
expect_docs "$ROLLED" 1382 "the rollup"
done_
