#!/usr/bin/env bash
# Sales: a year of order lines, and the report a finance team asks for, built
# from aggregations alone -- no rows leave the engine except the summary.
source "$(dirname "$0")/lib.sh"
IDX=sales
SUM=sales-monthly
PAGES=/tmp/sales-24-buckets.ndjson
ROWS=/tmp/sales-24-monthly.ndjson

# ask METHOD PATH FILE -- reqf, keeping the answer in $ANSWER for the checks
ANSWER=
ask() {
  ANSWER=$("${CURL[@]}" -X "$1" "$BS$2" -H 'Content-Type: application/json' --data-binary "@$3")
  printf '%s\n' "$ANSWER"
}

# expect EXPR WANT [what] -- a Python expression over the last answer's
# aggregations (`a`) must print WANT; `other` is the same for $OTHER, when it is
# set. The wanted numbers were counted from data/make-sales.py's output by a
# separate script, not copied from a run.
expect() {
  local got
  got=$(printf '%s' "$ANSWER" | python3 -c 'import json,sys
import os
d = json.load(sys.stdin); a = d.get("aggregations", {})
other = json.loads(os.environ.get("OTHER") or "{}").get("aggregations", {})
try: print(eval(sys.argv[1]))
except Exception as e: print("error: %r" % e)' "$1")
  if [ "$got" = "$2" ]; then
    printf '   \033[32mok\033[0m  %s%s\n' "$got" "${3:+ -- $3}"
  else
    printf '   \033[31mNOT WHAT WAS EXPECTED\033[0m  %s, expected %s%s\n' "$got" "$2" "${3:+ -- $3}" >&2
    _fails=$((_fails + 1))
  fi
}

step "an index shaped for aggregation: every field a keyword, a number or a date"
gone "/$IDX"; gone "/$SUM"
reqf PUT "/$IDX" requests/01-an-index-shaped-for-aggregation.json
green "$IDX"

step "a year of sales lines, one document per line sold"
note "generated by data/make-sales.py with a fixed seed; 3,000 ordinary lines and 4 rare ones"
ndjson "/$IDX/_bulk?refresh=wait_for" data/01-a-year-of-sales-lines-one.ndjson | clip 200
expect_docs "$IDX" 3004 "a year of sales"

step "every region, category and month: a composite, paged with after_key until it runs out"
note "a terms aggregation would have to guess a size; a composite hands back a cursor instead"
: > "$PAGES"
after=""
page=0
while :; do
  body=$(python3 -c 'import json,sys
b = json.load(open(sys.argv[1]))
if sys.argv[2]: b["aggs"]["lines"]["composite"]["after"] = json.loads(sys.argv[2])
print(json.dumps(b))' requests/02-every-region-category-and-month-a.json "$after")
  out=$("${CURL[@]}" -X GET "$BS/$IDX/_search" -H 'Content-Type: application/json' -d "$body")
  page=$((page + 1))
  [ "$page" = 1 ] && printf '%s\n' "$out" | clip 700
  read -r n after < <(printf '%s' "$out" | python3 -c 'import json,sys
agg = json.load(sys.stdin)["aggregations"]["lines"]
with open(sys.argv[1], "a") as f:
    for b in agg["buckets"]: f.write(json.dumps(b) + "\n")
print(len(agg["buckets"]), json.dumps(agg["after_key"], sort_keys=True, separators=(",", ":")) if agg["buckets"] and "after_key" in agg else "")' "$PAGES")
  note "page $page: $n buckets${after:+, after_key $after}"
  [ "$n" = 0 ] || [ -z "$after" ] && break
  [ "$page" -gt 50 ] && { echo "the composite never ran out of pages" >&2; exit 1; }
done
ANSWER=$(python3 -c 'import json,sys
bs = [json.loads(l) for l in open(sys.argv[1])]
print(json.dumps({"aggregations": {"n": len(bs), "keys": len({json.dumps(b["key"], sort_keys=True) for b in bs}),
  "docs": sum(b["doc_count"] for b in bs), "revenue": sum(b["revenue"]["value"] for b in bs)}}))' "$PAGES")
expect 'a["n"], a["keys"]' "(240, 240)" "5 regions x 4 categories x 12 months, none repeated across pages"
expect 'a["docs"], round(a["revenue"], 2)' "(3004, 1030908.54)" "every sale counted once, and the whole year's revenue"

step "a summary index built from those buckets -- a transform, done by hand"
note "_plugins/_transform and _plugins/_rollup are not answered by this node (see README), so the"
note "exported buckets are written back as documents: one per region, category and month"
reqf PUT "/$SUM" requests/03-a-summary-index-built-from-those.json
green "$SUM"
python3 - "$PAGES" > "$ROWS" <<'PY'
import json, sys
for line in open(sys.argv[1]):
    b = json.loads(line)
    k = b["key"]
    print(json.dumps({"index": {"_id": f'{k["region"]}|{k["category"]}|{k["month"]}'}}))
    print(json.dumps({"region": k["region"], "category": k["category"], "month": k["month"],
                      "orders": b["doc_count"], "units": int(b["units"]["value"]),
                      "revenue": round(b["revenue"]["value"], 2)}))
PY
ndjson "/$SUM/_bulk?refresh=wait_for" "$ROWS" | clip 200
expect_docs "$SUM" 240 "one document per composite bucket"

step "the summary answers what the raw index answers, from 240 documents instead of 3004"
note "--- the raw index"
ask GET "/$IDX/_search" requests/04-the-summary-answers-what-the-raw.json
raw=$ANSWER
note "--- the summary"
ask GET "/$SUM/_search" requests/04-the-summary-answers-what-the-raw.json
OTHER=$raw expect '[(b["key"], round(b["revenue"]["value"], 2)) for b in a["regions"]["buckets"]] == [(b["key"], round(b["revenue"]["value"], 2)) for b in other["regions"]["buckets"]]' \
  "True" "every region's revenue is the same from either index"
expect 'round(a["total"]["value"], 2)' "1030908.54" "the year's revenue, from the summary"
note "--- a question only the summary is cheap for: the three best months"
ANSWER=$("${CURL[@]}" -X GET "$BS/$SUM/_search" -H 'Content-Type: application/json' -d '{
  "size": 0,
  "aggs": { "months": {
    "date_histogram": { "field": "month", "calendar_interval": "month", "format": "yyyy-MM" },
    "aggs": { "revenue": { "sum": { "field": "revenue" } },
              "best": { "bucket_sort": { "sort": [ { "revenue": { "order": "desc" } } ], "size": 3 } } } } }
}')
printf '%s\n' "$ANSWER"
expect '[b["key_as_string"] for b in a["months"]["buckets"]]' "['2025-12', '2025-11', '2025-10']" "the last quarter, as the generator weighted it"

step "which region and channel pairs sell the most"
ask GET "/$IDX/_search" requests/05-which-region-and-channel-pairs-sell.json
expect '[b["key_as_string"] for b in a["pairs"]["buckets"]]' "['north|web', 'west|web', 'south|web', 'north|store', 'east|web']"
expect 'round(a["pairs"]["buckets"][0]["revenue"]["value"], 2)' "182720.74" "north through the web"

step "the products almost nobody bought"
ask GET "/$IDX/_search" requests/06-the-products-almost-nobody-bought.json
expect 'sorted((b["key"], b["doc_count"]) for b in a["hardly_sold"]["buckets"])' "[('globe', 1), ('hammock', 2), ('telescope', 1)]" "and nothing else"

step "the year in six buckets, whatever width that takes"
ask GET "/$IDX/_search" requests/07-the-year-in-six-buckets-whatever.json
expect 'a["year"]["interval"], len(a["year"]["buckets"])' "('3M', 4)" "the engine chose quarters: months would have been twelve buckets"
expect '[b["doc_count"] for b in a["year"]["buckets"]]' "[585, 636, 678, 1105]"

step "order sizes and quarters, named by hand and keyed"
ask GET "/$IDX/_search" requests/08-order-sizes-and-quarters-named-by.json
expect '[a["order_size"]["buckets"][k]["doc_count"] for k in ("small", "medium", "large")]' "[1783, 1006, 215]"
expect 'round(a["quarters"]["buckets"]["Q4"]["revenue"]["value"], 2)' "364103.81" "Q4 is a third of the year"

step "the biggest and the latest sale in each region"
ask GET "/$IDX/_search" requests/09-the-biggest-and-the-latest-sale.json
expect '[b["biggest"]["hits"]["hits"][0]["_id"] for b in a["regions"]["buckets"]]' "['SO-00903', 'SO-02289', 'SO-01014', 'SO-02379', 'SO-02291']"
expect '[b["latest"]["hits"]["hits"][0]["_source"]["sold_at"] for b in a["regions"]["buckets"]][-1]' "2025-12-31T18:34:00Z" "west's last sale of the year"

step "the shape of price, discount and revenue"
ask GET "/$IDX/_search" requests/10-the-shape-of-price-discount-and.json
expect '[(b["key"], round(b["price_paid_per_unit"]["value"], 2), round(b["plain_avg_price"]["value"], 2)) for b in a["by_category"]["buckets"]][1]' \
  "('electronics', 254.52, 273.67)" "a 20-unit order counts once in a plain average and twenty times in a weighted one"
expect 'round(a["discount"]["avg"], 4), round(a["discount"]["std_deviation"], 4), a["discount"]["max"]' "(0.082, 0.0575, 0.31)"
expect '{f["name"]: round(f["correlation"]["revenue"], 2) for f in a["together"]["fields"]}["quantity"] > 0' "True" "more units, more revenue"
note "the median and its absolute deviation are estimates; counted exactly they are 72.82 and 50.66"

step "regions ranked by margin, the weak ones dropped"
ask GET "/$IDX/_search" requests/11-regions-ranked-by-margin-the-weak.json
expect '[(b["key"], round(b["margin_pct"]["value"], 2)) for b in a["regions"]["buckets"]]' \
  "[('west', 36.17), ('north', 33.98), ('east', 32.59)]" "south (28.84) and central (24.12) fell below 30"

step "bulk orders, deep discounts, and everything else"
ask GET "/$IDX/_search" requests/12-bulk-orders-deep-discounts-and-everything.json
expect '[a["kinds"]["buckets"][k]["doc_count"] for k in ("bulk", "deep_discount", "neither")]' "[244, 127, 2642]" \
  "3013 in all: the filters overlap, nine sales are both"

step "central against the whole company, in one request"
ask GET "/$IDX/_search" requests/13-central-against-the-whole-company.json
expect 'round(a["central_revenue"]["value"], 2), a["company"]["doc_count"], round(a["company"]["revenue"]["value"], 2)' "(111189.49, 3004, 1030908.54)" \
  "the query scoped the first number; global ignored it"
expect 'round(a["central_discount"]["value"], 4), round(a["company"]["discount"]["value"], 4)' "(0.1777, 0.082)" "central discounts twice as deep"

step "what a missing field counts as"
ask GET "/$IDX/_search" requests/14-what-a-missing-field-counts-as.json
expect 'a["unrated"]["doc_count"], [b["doc_count"] for b in a["coupons"]["buckets"] if b["key"] == "(none)"][0]' "(574, 2553)"
expect 'round(a["rating_of_the_rated"]["value"], 2), round(a["rating_if_unrated_is_1"]["value"], 2)' "(3.96, 3.4)" \
  "the same field, averaged under two different beliefs about silence"

step "a value the documents do not store: the quarter, computed"
ask GET "/$IDX/_search" requests/15-a-value-the-documents-do-not.json
expect '[(b["key"], b["doc_count"]) for b in a["quarter"]["buckets"]]' "[('Q1', 585), ('Q2', 636), ('Q3', 678), ('Q4', 1105)]" \
  "the same counts date_range and auto_date_histogram gave"
expect '[(c["key"], c["doc_count"]) for c in a["quarter"]["buckets"][3]["basket"]["buckets"]]' "[('one or two', 746), ('several', 268), ('bulk', 91)]"

step "what this example leaves behind, checked rather than assumed"
expect_docs "$IDX" 3004 "the sales lines"
expect_docs "$SUM" 240 "the summary"
done_
